# Prompts

from .classifier_prompt import CLASSIFIER_SYSTEM_PROMPT, CLASSIFIER_USER_PROMPT_TEMPLATE
from .contribution_profile_prompt import (
    CONTRIBUTION_PROFILE_SYSTEM_PROMPT,
    CONTRIBUTION_PROFILE_USER_PROMPT_TEMPLATE,
    NOVEL_WORK_GUARD_EXAMPLE,
    NOVEL_WORK_GUARD_RULE,
)
from .decomposer_prompt import DECOMPOSER_SYSTEM_PROMPT, DECOMPOSER_USER_PROMPT_TEMPLATE

__all__ = [
    "CLASSIFIER_SYSTEM_PROMPT",
    "CLASSIFIER_USER_PROMPT_TEMPLATE",
    "CONTRIBUTION_PROFILE_SYSTEM_PROMPT",
    "CONTRIBUTION_PROFILE_USER_PROMPT_TEMPLATE",
    "DECOMPOSER_SYSTEM_PROMPT",
    "DECOMPOSER_USER_PROMPT_TEMPLATE",
    "NOVEL_WORK_GUARD_EXAMPLE",
    "NOVEL_WORK_GUARD_RULE",
]
